### ISSUE TITLE
Add support for API authentication

### ISSUE THREAD

**Issue by jonnyspringare** [Lundalogik/limeclient#2]
This limeclient library is used in the old autoimport module for Lime CRM, used by a lot of customers. Since limeclient right now only supports authentication by username/password, this causes problem when implementing Azure AD for the customer.

We should add a new login function with support for authentication with API key.

@FlippAre

**Comment by RasmusHeitmann** [comment]
Would be great, since this might also be considered a hurdle in e.g. moving to cloud.

**Comment by jensgustafsson** [comment]
Fixed in version 1.1.0 by commit 8b08e14a98a6fdb45162f3c66e03131e25dc8600.

**Beware**: The metadata API in lime-core doesn't support API keys but will be fixed by https://github.com/Lundalogik/lime-core/pull/1506

**Comment by RasmusHeitmann** [comment]
Not completely sure how the releases works, but when trying to install the newest autoimport, it has a dependency on limeclient 1.1.3 which it can't find. @jensgustafsson Do you need to publish it somehow perhaps?

**Comment by jensgustafsson** [comment]
> Not completely sure how the releases works, but when trying to install the newest autoimport, it has a dependency on limeclient 1.1.3 which it can't find. @jensgustafsson Do you need to publish it somehow perhaps?

Are you sure that you've configured the correct index url? That version exists on our PyPI.

**Comment by RasmusHeitmann** [comment]
> > Not completely sure how the releases works, but when trying to install the newest autoimport, it has a dependency on limeclient 1.1.3 which it can't find. @jensgustafsson Do you need to publish it somehow perhaps?
> 
> Are you sure that you've configured the correct index url? That version exists on our PyPI.

Not sure, but that is possible :) We just set the lime-client dependency to 1.0.3 instead, as we didn't need the api authentication possibility for now.
